name: Create Dev Scratch Org

on:
  workflow_dispatch:
    inputs:
      scratch_create_request_id:
        required: true
        type: integer

jobs:
    create-dev-org:
        name: "Create Dev Scratch Org"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:latest
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github-token }}
            env:
                DEV_HUB_AUTH_URL: "${{ secrets.dev-hub-auth-url }}"
                CUMULUSCI_SERVICE_github: "{ \"username\": \"${{ github.actor }}\", \"token\": \"${{ secrets.github-token }}\", \"email\": \"${{ secrets.gh-email }}\" }"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Set dev org as default org
              run: cci org default dev
            - name: Run dev_org flow
              run: cci flow run dev_org
            - name: Install coreapi
              run: pip install coreapi-cli
            - name: Save org to D2X Cloud
              run: \
                   export AUTH_URL=`sfdx org display --verbose --json -u ${{ repo.name }} | jq ".sfdxAuthUrl"`; \
                   export ORG_CONFIG=`cci org info --json | jq ". += {'sfdx_auth_url': $AUTH_URL}"`; \
                   coreapi headers add Authorization "Token ${{ secrets.d2x-cloud-base-url }}"
                   coreapi get ${{ secrets.d2x-cloud-base-url }}/docs/
                   coreapi action scratch-create-requests complete -p id=${{ inputs.scratch_create_request_id }} -p $ORG_CONFIG

              shell: bash
        secrets:
            d2x-cloud-base-url: ${{ secrets.D2X_CLOUD_BASE_URL }}
            d2x-cloud-token: ${{ secrets.D2X_CLOUD_TOKEN }}
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.GITHUB_TOKEN }}"
