on:
    workflow_dispatch:
        inputs:
            scratch_create_request_id:
                required: True
                type: number

jobs:
    create-dev-org:
        name: "Create Dev Scratch Org"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:prototype
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            env:
                D2X_CLOUD_BASE_URL: ${{ secrets.D2X_CLOUD_BASE_URL }}
                D2X_CLOUD_TOKEN: ${{ secrets.D2X_CLOUD_TOKEN }}
                DEV_HUB_AUTH_URL: "${{ secrets.DEV_HUB_AUTH_URL }}"
                CUMULUSCI_SERVICE_github: "{ \"username\": \"${{ github.actor }}\", \"token\": \"${{ secrets.GITHUB_TOKEN }}\", \"email\": \"${{ secrets.GH_EMAIL }}\" }"
                REPO_NAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
                SCRATCH_CREATE_REQUEST_ID: ${{ inputs.scratch_create_request_id }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Set feature org as default org
              run: cci org default feature
            - name: Install coreapi
              run: |
                   pip install coreapi-cli

            - name: Save org to D2X Cloud - ${{ inputs.scratch_create_request_id }}
              run: python d2x/save_org.py feature
              shell: bash
            - name: Run dev_org flow
              run: cci flow run dev_org


