on:
    workflow_dispatch:
        inputs:
            scratch_create_request_id:
                required: True
                type: integer

jobs:
    create-dev-org:
        name: "Create Dev Scratch Org"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:latest
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            env:
                D2X_CLOUD_BASE_URL: ${{ secrets.D2X_CLOUD_BASE_URL }}
                D2X_CLOUD_TOKEN: ${{ secrets.D2X_CLOUD_BASE_URL }}
                DEV_HUB_AUTH_URL: "${{ secrets.DEV_HUB_AUTH_URL }}"
                CUMULUSCI_SERVICE_github: "{ \"username\": \"${{ github.actor }}\", \"token\": \"${{ secrets.GITHUB_TOKEN }}\", \"email\": \"${{ secrets.GH_EMAIL }}\" }"
                REPO_NAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Set dev org as default org
              run: cci org default dev
            - name: Run dev_org flow
              run: cci flow run dev_org
            - name: Install coreapi
              run: pip install coreapi-cli
            - name: "Save org to D2X Cloud: ${{ github.event.input.scratch_create_request_id }}"
              run: |
                   export AUTH_URL=`sfdx org display --verbose --json -u $REPO_NAME__dev | jq ".sfdxAuthUrl"`
                   export ORG_CONFIG=`cci org info --json | jq ". += {'sfdx_auth_url': $AUTH_URL}"`
                   coreapi headers add Authorization "Token $D2X_CLOUD_TOKEN"
                   coreapi get $D2X_CLOUD_BASE_URL/docs/
                   coreapi action scratch-create-requests complete -p id=${{ inputs.scratch_create_request_id }} -p org_config="""$ORG_CONFIG"""

              shell: bash
